name: Pre-commit checks (black, isort, mypy, flake8, pytest)

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  install-and-test:

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10"]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1

    - name: Using poetry, install the package
      run: |
        poetry --version
        poetry install

    - name: Check installed packages (both conda and poetry/pip)
      run: |
        poetry env info
        pip list

    - name: Install pre-commit
      run: |
        poetry run pre-commit install

    - name: Run all pre-commit tests
      run: |
        poetry run pre-commit run --all-files
