name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

# This allows a subsequently queued workflow run to interrupt previous runs
# https://docs.github.com/en/actions/examples/using-concurrency-expressions-and-a-test-matrix#example-workflow
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
    - name: Install poetry
      run: pipx install poetry
#    - name: Install and configure Poetry
#      uses: snok/install-poetry@v1

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'

    - name: Using poetry, install the package
      run: |
        poetry --version
        poetry install

    - name: Check installed packages
      run: |
        poetry env info
        pip list

    - name: Install pre-commit
      run: |
        poetry run pre-commit install

    - name: Run all pre-commit tests
      run: |
        poetry run pre-commit run --all-files
